### PR TITLE
Re-add EuclideanRing instance

### LINKED ISSUE #8: Fixed isn't a Semiring
Quickcheck reveals the following properties don't actually hold:

- Associativity of multiplication
- Left and right distributivity

We might want to consider dropping `Semiring` and only providing a (commutative) additive `Monoid`. Multiplication would have to be provided as a function, just like we do for division.

We could perhaps provide an unsafe `Semiring` around a `newtype` for compatibility purposes, but I doubt many people are using this library anyway.

### PR DESCRIPTION
**Pull request by hdgarrood**
Closes #8. We should provide the numeric hierarchy instances for Fixed after all,
because they're useful, and law failures due to rounding errors are not
problematic enough to justify removing them; if Number can have them,
then Fixed should too. (Strict adherence to laws would even necessitate
removing the Semiring instance, as noted in #8.)

I've also deprecated the `approxDiv` function, because we can now use `/` instead.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I've just spotted that a) we should probably have `DivisionRing` too, and b) this is different from the previous `EuclideanRing` instance; the one I've added should correspond to normal division of real numbers, or at least as close as we can get to it with Fixed.

**Comment by hdgarrood** [comment]
Seems to work:
```
> import Prelude 
> import Data.Fi
Data.Field  Data.Fixed
> import Data.Fixed 
> x = from
fromInt     fromNumber  fromString
> x = fromInt 100 :: Fixed P1000
> recip x
(fromString "0.010" :: PfromString "1000")

> x * recip x
(fromString "1.000" :: PfromString "1000")

> y = fromInt 3 :: Fixed P1000
> x /y
(fromString "33.333" :: PfromString "1000")

> x /y * y
(fromString "99.999" :: PfromString "1000")
```

**Comment by paf31** [comment]
But `recip x` will be zero if `x` is large enough, breaking the laws, right?

**Comment by hdgarrood** [comment]
Yes, but you still get the closest representable value to the actual result - I think this is just another facet of the issue that multiplication can lose precision, e.g. squaring a number which is smaller than `10^(-precision/2)` will give an inexact result. If you want to use `Fixed p`, you have to be careful not to multiply by numbers which are too small (based on `p`), or equivalently divide by numbers which are too large.

**Pull request merged**
